# Generated by Django 2.1.15 on 2021-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkShortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_link', models.TextField()),
                ('has_link', models.TextField(unique=True)),
            ],
        ),
    ]
