# Generated by Django 2.1.15 on 2021-06-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkshortener',
            old_name='has_link',
            new_name='hash_link',
        ),
    ]
